/* eslint-disable*/
// Enum account_account_industrycode
export const enum account_account_industrycode {
  Accounting = 1,
  AgricultureandNonpetrolNaturalResourceExtraction = 2,
  BroadcastingPrintingandPublishing = 3,
  Brokers = 4,
  BuildingSupplyRetail = 5,
  BusinessServices = 6,
  Consulting = 7,
  ConsumerServices = 8,
  DesignDirectionandCreativeManagement = 9,
  DistributorsDispatchersandProcessors = 10,
  DoctorsOfficesandClinics = 11,
  DurableManufacturing = 12,
  EatingandDrinkingPlaces = 13,
  EntertainmentRetail = 14,
  EquipmentRentalandLeasing = 15,
  Financial = 16,
  FoodandTobaccoProcessing = 17,
  InboundCapitalIntensiveProcessing = 18,
  InboundRepairandServices = 19,
  Insurance = 20,
  LegalServices = 21,
  NonDurableMerchandiseRetail = 22,
  OutboundConsumerService = 23,
  PetrochemicalExtractionandDistribution = 24,
  ServiceRetail = 25,
  SIGAffiliations = 26,
  SocialServices = 27,
  SpecialOutboundTradeContractors = 28,
  SpecialtyRealty = 29,
  Transportation = 30,
  UtilityCreationandDistribution = 31,
  VehicleRetail = 32,
  Wholesale = 33,
}
  