/* eslint-disable*/
// Enum qooi_pricingerrorcode
export const enum qooi_pricingerrorcode {
  None = 0,
  DetailError = 1,
  MissingPriceLevel = 2,
  InactivePriceLevel = 3,
  MissingQuantity = 4,
  MissingUnitPrice = 5,
  MissingProduct = 6,
  InvalidProduct = 7,
  MissingPricingCode = 8,
  InvalidPricingCode = 9,
  MissingUOM = 10,
  ProductNotInPriceLevel = 11,
  MissingPriceLevelAmount = 12,
  MissingPriceLevelPercentage = 13,
  MissingPrice = 14,
  MissingCurrentCost = 15,
  MissingStandardCost = 16,
  InvalidPriceLevelAmount = 17,
  InvalidPriceLevelPercentage = 18,
  InvalidPrice = 19,
  InvalidCurrentCost = 20,
  InvalidStandardCost = 21,
  InvalidRoundingPolicy = 22,
  InvalidRoundingOption = 23,
  InvalidRoundingAmount = 24,
  PriceCalculationError = 25,
  InvalidDiscountType = 26,
  DiscountTypeInvalidState = 27,
  InvalidDiscount = 28,
  InvalidQuantity = 29,
  InvalidPricingPrecision = 30,
  MissingProductDefaultUOM = 31,
  MissingProductUOMSchedule = 32,
  InactiveDiscountType = 33,
  InvalidPriceLevelCurrency = 34,
  PriceAttributeOutOfRange = 35,
  BaseCurrencyAttributeOverflow = 36,
  BaseCurrencyAttributeUnderflow = 37,
  Transactioncurrencyisnotsetfortheproductpricelistitem = 38,
}
  